name: Assign AI Workflow Automation Specialist

on:
  issues:
    types: [opened, labeled]

permissions:
  issues: write
  contents: read

jobs:
  assign-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get issue labels
        id: labels
        run: |
          LABELS=$(jq -r '.issue.labels[].name' <<< "${{ toJSON(github.event) }}")
          echo "labels=$LABELS" >> $GITHUB_OUTPUT

      - name: Evaluate assignment rules
        id: rules
        run: |
          # Example: only assign if label 'automation' exists and 'blocked' does not
          if [[ "${{ steps.labels.outputs.labels }}" == *"automation"* ]] && [[ "${{ steps.labels.outputs.labels }}" != *"blocked"* ]]; then
            echo "assign=true" >> $GITHUB_OUTPUT
          else
            echo "assign=false" >> $GITHUB_OUTPUT
          fi

      - name: Assign AI Agent
        if: steps.rules.outputs.assign == 'true'
        run: |
          echo "Assigning AI Workflow Automation Specialist to issue #${{ github.event.issue.number }}"
          gh issue edit ${{ github.event.issue.number }} --add-assignee "ai-workflow-specialist"
